#!/usr/bin/env bash
# Transfers a file from our client to a server

# Check if the number of arguments is less than 4
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  # Use SCP to transfer the file
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
