#!/bin/bash

# Check for root privileges
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run as root or with sudo."
    exit 1
fi

# Update and install Nginx with -y option
echo -e "Updating and installing Nginx.\n"
if ! apt-get update -y -qq || ! apt-get install nginx -y; then
    echo "Failed to install Nginx. Exiting."
    exit 1
fi

# Start Nginx service
service nginx start

# Give the user ownership to website files for easy editing
chown -R "$USER":"$USER" /var/www/html
chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index with "Hello World!"
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restart Nginx using /etc/init.d/nginx
/etc/init.d/nginx restart

echo -e "\nCompleted. ✅\n"
