#!/usr/bin/env bash

# Check for root privileges
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run as root or with sudo."
    exit 1
fi

# Check if Nginx is already installed
if command -v nginx &> /dev/null; then
    echo "Nginx is already installed. Exiting."
    exit 0
fi

echo -e "Updating and installing Nginx.\n"
if ! sudo apt-get update -y -qq || ! sudo apt-get install nginx -y; then
    echo "Failed to install Nginx. Exiting."
    exit 1
fi

echo -e "\nSetting up some minor stuff.\n"

# Start nginx service
sudo systemctl start nginx
sudo systemctl enable nginx

# Allowing nginx on firewall
if command -v ufw &> /dev/null; then
    sudo ufw allow 'Nginx HTTP'
else
    echo "UFW is not installed. Install it before using this script."
    exit 1
fi

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restarting nginx
sudo systemctl restart nginx

echo -e "\nCompleted. ✅\n"
