#!/usr/bin/env bash

# Check if HAProxy is installed
if command -v haproxy &>/dev/null; then
    echo "HAProxy is already installed. Skipping installation."
else
    # Install HAProxy
    sudo apt-get update
    sudo apt-get install -y haproxy
fi

# Check if HAProxy configuration exists
haproxy_config="/etc/haproxy/haproxy.cfg"
if [ -e "$haproxy_config" ]; then
    echo "HAProxy is already configured. Skipping configuration."
else
    # Configure HAProxy
    sudo bash -c 'cat << EOF > /etc/haproxy/haproxy.cfg
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server [STUDENT_ID]-web-01 [web-01-IP]:80 check
    server [STUDENT_ID]-web-02 [web-02-IP]:80 check
EOF'

    # Restart HAProxy to apply the configuration
    sudo service haproxy restart
fi
