#!/usr/bin/env bash

# This Bash script configures a new Ubuntu machine to match the task requirements

# Check if Nginx is installed
if [ ! -x "$(command -v nginx)" ]; then
  sudo apt-get update
  sudo apt-get install -y nginx
fi

# Get the hostname of the server
HOSTNAME=$(hostname)

# Check if the configuration file exists and add the custom header
CONFIG_FILE="/etc/nginx/sites-available/custom_header"
if [ ! -e "$CONFIG_FILE" ]; then
  echo "add_header X-Served-By $HOSTNAME;" | sudo tee "$CONFIG_FILE"
fi

# Check if the symbolic link doesn't exist, then create it
SYMBOLIC_LINK="/etc/nginx/sites-enabled/custom_header"
if [ ! -e "$SYMBOLIC_LINK" ]; then
  sudo ln -s "$CONFIG_FILE" "$SYMBOLIC_LINK"
fi

# Remove the default symbolic link to the default configuration
sudo rm -f /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo systemctl restart nginx

# Exit with success status
exit 0
