#!/usr/bin/env bash
# Configures Nginx to listen on port 80

# Remove existing Nginx configuration
sudo rm /etc/nginx/sites-available/default

# Create a new Nginx configuration
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restar
