#!/bin/bash

# Set default incoming policy to deny
sudo ufw default deny incoming

# Allow incoming traffic on specific TCP ports
sudo ufw allow 22/tcp     # SSH
sudo ufw allow 443/tcp    # HTTPS SSL
sudo ufw allow 80/tcp     # HTTP

# Enable UFW firewall
sudo ufw enable
