#!/usr/bin/env bash
# This script runs the whoami command under the specified user.

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

username="$1"
su "$username" -s /bin/bash -c 'whoami'
